# Generated by Django 3.1.7 on 2021-05-06 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='count',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
