# Generated by Django 3.1.7 on 2021-05-06 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210506_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
