# Generated by Django 3.1.7 on 2021-05-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210506_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookstore',
            new_name='StoreInventory',
        ),
    ]
